### ISSUE TITLE
上传卡死

### ISSUE THREAD

**Issue by kabaka9527** [ProudCarrotG/autoPutPathtoAlist#1]
在小带宽场景中，长时间上传较多大文件可能卡死

**Comment by ProudCarrotG** [comment]
请问有没有保留错误信息？
是在一个文件上传时卡死还是某个文件上传完成后卡死？
大文件的大小大概是多大？数量？
如果是某个文件上传时卡死，在alist服务器上是否有这个文件存在？（即使是不完全的该文件）

**Comment by kabaka9527** [comment]
> 请问有没有保留错误信息？
> 是在一个文件上传时卡死还是某个文件上传完成后卡死？
> 大文件的大小大概是多大？数量？
> 如果是某个文件上传时卡死，在alist服务器上是否有这个文件存在？（即使是不完全的该文件）

没有错误信息，在上传一些文件后（5-8个包）
文件大小在80MB左右，数量为50左右，卡住后alist中无文件存在

**Comment by ProudCarrotG** [comment]
知道了
如果是急需将这些文件上传的话，可以尝试重启程序，程序会自动跳过卡死前上传好的文件，然后尝试上传之前失败的文件
我会尽快处理这个问题
如果有出现其他问题，也请向我反馈

**Comment by ProudCarrotG** [comment]
经测试，卡死原因为发送http请求时，，程序一直在积极等待服务器响应，当宽带较小、服务器不稳定、传输文件过大时，都可能会出现文件传输多次中断，此时程序就会进入卡死状态
为更加清晰地观察文件上传情况，为上传添加了进度条显示
为防止服务器长时间不回应，添加超时参数，在settings文件中可以自定义超时，当传输响应超时时，会抛出异常，将文件加入失败队列
在尝试所有文件上传后，可以重新设置超时参数，可以重新尝试上传失败文件
感谢你的反馈！

**Comment by kabaka9527** [comment]
> 经测试，卡死原因为发送http请求时，，程序一直在积极等待服务器响应，当宽带较小、服务器不稳定、传输文件过大时，都可能会出现文件传输多次中断，此时程序就会进入卡死状态
> 为更加清晰地观察文件上传情况，为上传添加了进度条显示
> 为防止服务器长时间不回应，添加超时参数，在settings文件中可以自定义超时，当传输响应超时时，会抛出异常，将文件加入失败队列
> 在尝试所有文件上传后，可以重新设置超时参数，可以重新尝试上传失败文件
> 感谢你的反馈！

感谢修复，能否添加一个可选项，在上传时删除alist对应目录中的文件再上传，以保证上传文件为最新

**Comment by ProudCarrotG** [comment]
:kissing_heart:已添加至计划中
